stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install --frozen-lockfile --non-interactive
    - yarn run typecheck
    - yarn run lint
    - yarn run test --ci --coverage --reporters=default --reporters=jest-junit
    - yarn run build
  coverage: '/Statements\s*:\s*(\d+\.\d+)%/'
  tags:
    - nodejs-8
  artifacts:
    paths:
      - dist/
    reports:
      junit: junit.xml

publish:
  stage: deploy
  only:
    refs:
      - master
  script:
    - npx @manuscripts/publish
  tags:
    - nodejs-8
